import type { Component } from 'vue';

import {
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  BarChartOutlined,
  BookOutlined,
  BranchesOutlined,
  CodeOutlined,
  ClockCircleOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DeleteOutlined,
  DeploymentUnitOutlined,
  ExperimentOutlined,
  FileSearchOutlined,
  HomeOutlined,
  InboxOutlined,
  LineChartOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  MobileOutlined,
  MonitorOutlined,
  PhoneOutlined,
  PlusCircleOutlined,
  ProfileOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  RobotOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  SettingOutlined,
  TrophyOutlined,
  TeamOutlined,
  UnorderedListOutlined,
  UserOutlined,
  WarningOutlined,
} from '@ant-design/icons-vue';

const iconMap = {
  alert: AlertOutlined,
  apartment: ApartmentOutlined,
  api: ApiOutlined,
  'area-chart': BarChartOutlined,
  barChart: BarChartOutlined,
  book: BookOutlined,
  branches: BranchesOutlined,
  building: ApartmentOutlined,
  clock: ClockCircleOutlined,
  code: CodeOutlined,
  'code-sandbox': CodeOutlined,
  'customer-service': CustomerServiceOutlined,
  dashboard: DashboardOutlined,
  delete: DeleteOutlined,
  'deployment-unit': DeploymentUnitOutlined,
  experiment: ExperimentOutlined,
  'file-search': FileSearchOutlined,
  home: HomeOutlined,
  inbox: InboxOutlined,
  'line-chart': LineChartOutlined,
  list: UnorderedListOutlined,
  mail: MailOutlined,
  menu: MenuOutlined,
  message: MessageOutlined,
  mobile: MobileOutlined,
  monitor: MonitorOutlined,
  phone: PhoneOutlined,
  plusCircle: PlusCircleOutlined,
  'plus-circle': PlusCircleOutlined,
  profile: ProfileOutlined,
  questionCircle: QuestionCircleOutlined,
  'question-circle': QuestionCircleOutlined,
  read: ReadOutlined,
  robot: RobotOutlined,
  safety: SafetyCertificateOutlined,
  schedule: ScheduleOutlined,
  setting: SettingOutlined,
  settings: SettingOutlined,
  shield: TeamOutlined,
  team: TeamOutlined,
  ticket: ProfileOutlined,
  trophy: TrophyOutlined,
  unorderedList: UnorderedListOutlined,
  'unordered-list': UnorderedListOutlined,
  user: UserOutlined,
  warning: WarningOutlined,
};

export function getMenuIconComponent(icon?: string | Component): Component | undefined {
  if (!icon || typeof icon !== 'string') {
    return icon as Component | undefined;
  }

  const normalized = icon
    .replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`)
    .replace(/^-/, '');

  return iconMap[normalized as keyof typeof iconMap];
}
